### PR TITLE
build: do not version libpmi.so or libpmi2.so

### LINKED ISSUE #28: libpmi2.so installed with wrong so version
At some point the flux libpmi2.so so version was incremented so we install `/usr/lib64/flux/libpmi2.so.1` instead of `/usr/lib64/flux/libpmi2.so.0`. All mpi apps compiled within the standard environment will be looking SONAME of `libpmi2.so.0`, so this thwarts our attempt to prepend `/usr/lib64/flux` to `LD_LIBRARY_PATH` to point MPI applications launched under flux to a flux-provided PMI library.

### PR DESCRIPTION
**Pull request by grondo**
Do not add version information to libpmi.so nor libpmi.so.

Fixes #28

### CODE REVIEW

**Comment by grondo** [comment]
Restarted a builder that hung during `apt update`

**Comment by grondo** [comment]
Rebased on current master.

**Comment by dongahn** [comment]
This looks good to me. Mind if I merge this so that I can build UQP team a new version that can launch their app?

**Comment by grondo** [comment]
Yes, please. It has just been waiting for someone to merge it! :-)

**Comment by grondo** [comment]
Thanks!

**Pull request merged**
